const menu = [
  {
    id: 1,
    name: 'Pancake Stack',
    category: 'breakfast',
    description: 'Fluffy pancakes served with maple syrup and butter.',
    price: '$5.99',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 2,
    name: 'Omelette Deluxe',
    category: 'breakfast',
    description: 'Three-egg omelette with cheese, veggies, and ham.',
    price: '$6.50',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 3,
    name: 'French Toast',
    category: 'breakfast',
    description: 'Classic French toast topped with powdered sugar.',
    price: '$5.75',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 4,
    name: 'Club Sandwich',
    category: 'lunch',
    description: 'Triple-decker sandwich with turkey, bacon, and lettuce.',
    price: '$7.99',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 5,
    name: 'Grilled Chicken Salad',
    category: 'lunch',
    description: 'Fresh salad topped with grilled chicken and house dressing.',
    price: '$8.25',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 6,
    name: 'Veggie Wrap',
    category: 'lunch',
    description: 'Whole wheat wrap filled with seasonal grilled veggies.',
    price: '$6.75',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 7,
    name: 'Classic Cheeseburger',
    category: 'lunch',
    description: 'Beef patty with cheddar, lettuce, tomato, and pickles.',
    price: '$9.00',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 8,
    name: 'Vanilla Milkshake',
    category: 'shakes',
    description: 'Creamy vanilla shake topped with whipped cream.',
    price: '$3.99',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 9,
    name: 'Strawberry Smoothie',
    category: 'shakes',
    description: 'Fresh strawberry blend with yogurt and honey.',
    price: '$4.50',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 10,
    name: 'Chocolate Fudge Shake',
    category: 'shakes',
    description: 'Rich chocolate shake with fudge drizzle and sprinkles.',
    price: '$4.25',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 11,
    name: 'Avocado Toast',
    category: 'breakfast',
    description: 'Sourdough toast topped with smashed avocado and spices.',
    price: '$6.00',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 12,
    name: 'Caesar Salad',
    category: 'lunch',
    description:
      'Romaine lettuce with Caesar dressing, croutons, and parmesan.',
    price: '$7.25',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 13,
    name: 'Berry Blast Shake',
    category: 'shakes',
    description: 'Mixed berries and banana with a yogurt base.',
    price: '$4.75',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 14,
    name: 'Scrambled Eggs & Toast',
    category: 'breakfast',
    description: 'Light and fluffy eggs served with buttery toast.',
    price: '$5.50',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 15,
    name: 'BLT Sandwich',
    category: 'lunch',
    description: 'Bacon, lettuce, and tomato on toasted bread.',
    price: '$6.99',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 16,
    name: 'Mango Shake',
    category: 'shakes',
    description: 'Tropical mango shake made with fresh mango pulp.',
    price: '$4.00',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 17,
    name: 'Egg Benedict',
    category: 'breakfast',
    description: 'Poached eggs with hollandaise sauce on an English muffin.',
    price: '$7.50',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 18,
    name: 'Tuna Salad Wrap',
    category: 'lunch',
    description: 'Whole wheat wrap with tuna salad and lettuce.',
    price: '$7.75',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 19,
    name: 'Mint Chocolate Shake',
    category: 'shakes',
    description: 'Minty fresh shake with chocolate chips.',
    price: '$4.30',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 20,
    name: 'Breakfast Burrito',
    category: 'breakfast',
    description: 'Tortilla filled with eggs, cheese, and sausage.',
    price: '$6.85',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 21,
    name: 'Chicken Quesadilla',
    category: 'lunch',
    description: 'Grilled tortilla stuffed with chicken, cheese, and peppers.',
    price: '$8.50',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 22,
    name: 'Blueberry Pancakes',
    category: 'breakfast',
    description: 'Pancakes loaded with blueberries and topped with syrup.',
    price: '$6.25',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 23,
    name: 'Iced Mocha Shake',
    category: 'shakes',
    description: 'Coffee-infused chocolate shake with whipped cream.',
    price: '$4.65',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 24,
    name: 'Greek Salad',
    category: 'lunch',
    description: 'Tomatoes, cucumbers, feta cheese, and olives in vinaigrette.',
    price: '$7.50',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 25,
    name: 'Banana Protein Shake',
    category: 'shakes',
    description: 'Protein-packed banana shake perfect for post-workout.',
    price: '$4.95',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 26,
    name: 'Hash Browns',
    category: 'breakfast',
    description: 'Golden and crispy shredded potatoes.',
    price: '$3.50',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 27,
    name: 'BBQ Chicken Sandwich',
    category: 'lunch',
    description: 'Tender BBQ chicken served on a toasted bun.',
    price: '$8.75',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 28,
    name: 'Peanut Butter Shake',
    category: 'shakes',
    description: 'Creamy peanut butter shake with a hint of chocolate.',
    price: '$4.80',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 29,
    name: 'Fruit & Yogurt Parfait',
    category: 'breakfast',
    description: 'Layers of granola, yogurt, and seasonal fruits.',
    price: '$5.25',
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 30,
    name: 'Falafel Wrap',
    category: 'lunch',
    description: 'Crispy falafel balls with veggies and tahini in pita bread.',
    price: '$7.95',
    image: 'https://via.placeholder.com/150',
  },
];
